#!/bin/bash
echo ""
echo "installing ..."
echo ""
termux-setup-storage & sleep 5 &>/dev/null
pkg update -y

echo ""
echo " Installing x11 and tur-repo..."
echo ""

pkg install x11-repo tur-repo -y 

echo ""
echo ""
echo "installing termux-x11 and hangover-wine packages"


if pkg install wget unzip hangover-wine mesa-vulkan-icd-freedreno-dri3  -y
then
  echo "Hangover-Wine  is installed"
else
  echo " packages installation is failed please check your internet connection"
fi

if pkg install termux-x11-nightly -y & sleep 5
then
  echo "termux-x11 is installed"
else
  echo "Termux-x11 is not Installed"
fi
sleep 1
clear


  sleep 3
  cd ~
  echo "Downloading WinePrefix ..."
wget https://github.com/gamextra4u/Blender-on-Termux/releases/download/0.1/prefix.tar.gz

  echo "Extracting Prefix, Please Wait ...."
tar -xvf prefix.tar.gz .
  
echo "Downloading Blender-4.3.0-windows-arm64.... "

wget https://ftp.halifax.rwth-aachen.de/blender/release/Blender4.3/blender-4.3.0-windows-arm64.zip
  
echo " extracting zip file , please wait..."
  unzip blender-4.3.0-windows-arm64.zip &>/dev/null
  rm blender-4.3.0-windows-arm64.zip 
  mv blender-4.3.0-windows-arm64 blender-arm64
  mv blender-arm64 $HOME/.wine/dosdevices/c:/'Program Files'/                                    
  
  echo ""
echo " successfully extracted "
  
  sleep 3
  
  echo " Downloading Blender starting scripts..."
   wget https://raw.githubusercontent.com/gamextra4u/Blender-on-Termux/main/blender
chmod +x blender 
mv blender $PREFIX/bin
  
  echo ""
echo " Scripts installed"
echo ""
  clear
echo ""
echo " Installation finished. To start Blender Type `blender` "
  